# Configuration for generating task 4 interpretability artefacts.
features:
  source_table: artifacts/task1/source_features.csv
  target_table: artifacts/task1/target_features.csv

modeling:
  features:
    label_column: label
    feature_columns: null
    exclude_columns:
      - dataset
      - file_id
      - file_path
      - channel
      - segment_index
      - start_sample
      - end_sample
      - selection_score
      - label_code
  alignment:
    enabled: true
    epsilon: 1.0e-6
  split:
    test_size: 0.25
    random_state: 42
    stratify: true
  model:
    penalty: l2
    C: 1.5
    solver: lbfgs
    max_iter: 500
    multi_class: auto
    class_weight: balanced
  cross_validation:
    enabled: true
    folds: 5
    shuffle: true
  permutation_importance:
    enabled: false

time_frequency:
  stft:
    nperseg: 512
    noverlap: 256
    nfft: 1024
    window: hann
  cwt:
    wavelet: ricker
    min_scale: 1.0
    max_scale: 128.0
    num_scales: 64
  mel:
    num_mels: 64
    fmin: 20.0
    fmax: 20000.0
    power: 2.0
    log_amplitude: true
  consistency_bins: 64

pseudo_label:
  enabled: true
  confidence_threshold: 0.95
  max_iterations: 2
  max_ratio: 0.5
  consistency_threshold: 0.6

global_importance:
  method: auto
  shap_background: 200
  shap_nsamples: 200
  top_n: 20

domain_shift:
  top_n: 20

local_explanation:
  dataset: target
  indices:
    - 0
  index: 0
  class: null
  method: auto
  top_n: 10
  shap:
    background: 200
    nsamples: 200
  lime:
    num_samples: 5000
    random_state: 42
  cluster:
    enabled: true
    n_clusters: 3
    random_state: 42
    top_n: 12

outputs:
  directory: artifacts/task4
  global_feature_table: global_feature_effects.csv
  global_category_table: global_feature_categories.csv
  domain_shift_table: domain_shift_contributions.csv
  local_explanations: local_explanation.csv
  global_plot: global_importance.png
  domain_shift_plot: domain_shift.png
  local_plot: local_explanation.png
  local_cluster_assignments: local_cluster_assignments.csv
  local_cluster_profiles: local_cluster_profiles.csv
  local_cluster_plot: local_cluster_heatmap.png
  metrics: interpretability_summary.json
