# Configuration for training the source-domain diagnostic model (task 2).
features:
  table_path: artifacts/task1/source_features.csv
  label_column: label
  feature_columns: null  # Use automatic numeric feature discovery
  exclude_columns:
    - dataset
    - file_id
    - file_path
    - channel
    - segment_index
    - start_sample
    - end_sample
    - selection_score
    - label_code

split:
  test_size: 0.25
  random_state: 42
  stratify: true

model:
  penalty: l2
  C: 1.5
  solver: lbfgs
  max_iter: 500
  class_weight: balanced

alignment:
  enabled: true
  epsilon: 1.0e-6

cross_validation:
  enabled: true
  folds: 5
  shuffle: true

interpretability:
  permutation_importance:
    enabled: true
    n_repeats: 10
    random_state: 42
    scoring: f1_macro

outputs:
  directory: artifacts/task2
  metrics_file: metrics.json
  classification_report: classification_report.csv
  confusion_matrix: confusion_matrix.csv
  coefficient_importance: coefficient_importance.csv
  permutation_importance: permutation_importance.csv
  predictions: predictions.csv
  model_path: source_domain_model.joblib
  feature_summary: feature_summary.csv
  features_used: features_used.txt
  model_comparison: model_comparison.csv

benchmarks:
  - name: "随机森林"
    type: random_forest
    params:
      n_estimators: 300
      max_depth: null
      class_weight: balanced
  - name: "梯度提升"
    type: gradient_boosting
    params:
      n_estimators: 200
      learning_rate: 0.05
      max_depth: 3
  - name: "支持向量机"
    type: svc
    params:
      C: 5.0
      kernel: rbf
      gamma: scale
      probability: true
  - name: "极端随机森林"
    type: extra_trees
    params:
      n_estimators: 400
      max_depth: null
      random_state: 42
      class_weight: balanced
  - name: "多层感知机"
    type: mlp
    params:
      hidden_layer_sizes: [128, 64]
      activation: relu
      alpha: 0.0005
      random_state: 42
  - name: "K近邻分类器"
    type: knn
    params:
      n_neighbors: 7
      weights: distance
  - name: "朴素贝叶斯"
    type: gaussian_nb
    params: {}
