# Configuration driving the task 3 transfer learning pipeline.
features:
  source_table: artifacts/task1/source_features.csv
  target_table: artifacts/task1/target_features.csv
  metadata_columns:
    - file_id
    - channel
    - segment_index
    - start_sample
    - end_sample
    - rpm

modeling:
  features:
    label_column: label
    feature_columns: null
    exclude_columns:
      - dataset
      - file_id
      - file_path
      - channel
      - segment_index
      - start_sample
      - end_sample
      - selection_score
      - label_code
  alignment:
    enabled: true
    epsilon: 1.0e-6
  split:
    test_size: 0.25
    random_state: 42
    stratify: true
  model:
    penalty: l2
    C: 1.5
    solver: lbfgs
    max_iter: 500
    multi_class: auto
    class_weight: balanced
  cross_validation:
    enabled: true
    folds: 5
    shuffle: true
  permutation_importance:
    enabled: false

time_frequency:
  stft:
    nperseg: 512
    noverlap: 256
    nfft: 1024
    window: hann
  cwt:
    wavelet: ricker
    min_scale: 1.0
    max_scale: 128.0
    num_scales: 64

pseudo_label:
  enabled: true
  confidence_threshold: 0.95
  max_iterations: 2
  max_ratio: 0.5

outputs:
  directory: artifacts/task3
  predictions_initial: target_predictions_initial.csv
  predictions_final: target_predictions.csv
  pseudo_labels: pseudo_labels.csv
  pseudo_history: pseudo_history.csv
  alignment_before: alignment_before.csv
  alignment_after: alignment_after.csv
  combined_before: combined_features_before.csv
  combined_aligned: combined_features_aligned.csv
  time_frequency_features: time_frequency_features.txt
  metrics: metrics.json
  embedding_before: tsne_before.png
  embedding_after: tsne_after.png
  model_path: transfer_model.joblib
  pseudo_history_plot: 伪标签演化曲线.png
  tf_feature_plot: 多模态特征分布对比.png
  tf_example_plot: 多模态时频示例.png
  tf_example_data: 多模态时频示例数据.npz
  tf_example_metadata: 多模态时频示例信息.json
